version: "3.9"
services:
  auth-server:
    image: "gbarboza/spring-auth-server:1.0.6"
    ports:
      - "8080:8080"
    environment:
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_SCHEMA: spring
    depends_on:
      - database
  database:
    container_name: database
    image: "mysql:8"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "spring"

